# Generated by Django 4.2.23 on 2025-08-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_amount_ingredient_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
